global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: proteus-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000

  - job_name: proteus-dispatcher
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8002

  - job_name: proteus-worker-fast
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8003

  - job_name: proteus-worker-browser
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8004

  - job_name: proteus-worker-stealth
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8005

  - job_name: proteus-worker-external
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8006
